configuration:
  #unsetting widgets (i.e. captchas)
  unset: [foo, bazz/foo, bazz/bazz/bar]
  #options for form instanciation
  options: {foo: bar, bazz: foo}
  #arguments for form instanciation
  arguments: {foo: bazz}
  #save the form if its valid?
  withSave: true
  #the form to instanciate
  formClass: rsFormTesterForm
  #show output (recommend)
  verbose: true

#sets of data that should pass the validation
pass:
  -
    #options override for this set
    _options: {foo: bazz, bazz: bar}
    #arguments override for this set
    _arguments: {foo: foo}
    bar: bazz
    bazz:
      bar: foo
      bazz:
        foo: bar
  -
 #   foo: bar
    bar: bazz
    bazz:
      bar: foo
#      foo: bar
      bazz:
        foo: bar
        bar: foo

fail:
  -
    _expectedErrors: [foo, bazz/foo, bazz/bazz/bar]
    foo: foo
    bar: bar
    bazz:
      foo: foo
      bar: foo
      bazz:
#        foo: bar
        bar: foo
